### ISSUE TITLE
Browser does not follow contextmenu url

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-context-menu#1]
I've created a context menu on the following fragment:

ContextMenu::begin(['items'=>[['label'=>'Download', 'url'=>['file/download','id' => $this->id, 'inline' => false]],['label'=>'Delete', 'url'=>['file/delete','id' => $this->id]]]]);
        echo Html::a('<div class="col-xs-1" style="margin-bottom: 20px; text-align: center;">' . Icon::show($icontype,['class'=>'fa-3x']) . '<br>' . $this->filename . '</div>',['file/download','id' => $this->id]);
ContextMenu::end();

When I render this in the browser, I get the context menu, it activates on right click, when I hover over "Download" I see the url in the browser status bar. However, left clicking on "Download" does not make the browser follow the link. Is there something missing in the above code?

**Comment by kartik-v** [comment]
It seems to occur with [source plugin as well](https://github.com/sydcanem/bootstrap-contextmenu). Typically context menu is used for triggering javascript coded actions on click of each menu item.

**Comment by pgyf** [comment]
I modified the JS,  see  

https://github.com/liyunfang/yii2-contextmenu

**Comment by studio255** [comment]
I have the same Problem. I want a normal Link in the ContextMenu which is not working.

```
ContextMenu::begin([
    'items'=>[
    ['label'=>'Go to Page', 'url'=>'/test/url'],
],
]);
```

When i right click the Menu is opening, but when i click on the url nothing will happen. 

By the way, are there setting to make the Plugin work on a left click?

Thanks!

**Comment by studio255** [comment]
Thanks for the Update! Works now, great.
